---
title: "Demo of Collapse funcationality"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Demo of Collapse funcationality}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(cityClimateHealth)
```

```{r exposures}
library(dlnm)
library(gnm)
library(ggplot2)
library(data.table)

# create exposure matrix
exposure_columns <- list(
  "date" = "date",
 "exposure" = "tmax_C",
 "geo_unit" = "TOWN20",
 "geo_unit_grp" = "COUNTY20"
)

## basic
exposure_mat <- 
  make_exposure_matrix(
    subset(ma_exposure, TOWN20 %in% c('BOSTON', 'CHELSEA')),
    exposure_columns, 
    time_subset = list(month = 5:9)
)
head(exposure_mat)

## group 
exposure_mat <- 
  make_exposure_matrix(
    subset(ma_exposure, TOWN20 %in% c('BOSTON', 'CHELSEA')),
    exposure_columns, 
    time_subset = list(month = 5:9), 
    grp_level = T,
    keep_unit_exposures = F
  )
head(exposure_mat)

## group but keep unit exposures
exposure_mat <- 
  make_exposure_matrix(
    subset(ma_exposure, TOWN20 %in% c('BOSTON', 'CHELSEA')),
    exposure_columns, 
    time_subset = list(month = 5:9), 
    grp_level = T,
    keep_unit_exposures = T
  )
head(exposure_mat)

```


Now try with outcomes

```{r outcomes}

# create outcome table
outcome_columns <- list(
 "date" = "date",
 "outcome" = "daily_deaths",
 "factor" = c('age_grp', 'sex'),
 "geo_unit" = "TOWN20",
 "geo_unit_grp" = "COUNTY20"
)

boston_deaths <- subset(ma_deaths, TOWN20 %in% c('BOSTON', 'CHELSEA'))
head(boston_deaths)

## basic
outcomes_tbl <- make_outcome_table(
  boston_deaths,  
  outcome_columns,
  time_subset = list(month = 5:9)
)

head(outcomes_tbl)

## group
outcomes_tbl <- make_outcome_table(
  boston_deaths,  
  outcome_columns,
  time_subset = list(month = 5:9),
  grp_level = T,
  keep_unit_outcomes = F
)

head(outcomes_tbl)

## group but keep unit outcomes
outcomes_tbl <- make_outcome_table(
  boston_deaths,  
  outcome_columns,
  time_subset = list(month = 5:9),
  grp_level = T,
  keep_unit_outcomes = T
)

head(outcomes_tbl)

```
